@startuml sample_graph
    (0) -left- (1)
    (0) -- (2)
    (0) -- (5)
    (0) -right- (6)
    (3) -- (5)
    (3) -left- (4)
    (4) -- (5)
    (4) -up- (6)
    (7) -right- (8)
    (9) -- (10)
    (9) -- (11)
    (9) -- (12)
    (11) -right- (12)
@enduml